pipeline:
  build_sysroot:
    image: debian:buster
    commands:
      - apt-get update && apt-get -y install build-essential git mercurial subversion gperf gettext libtool libtool-bin cmake yasm zlib1g-dev autoconf pkg-config autopoint wget curl libgles2-mesa-dev&&  update-ca-certificates
      - ./extra.sh
  build:
    image: debian:buster
    commands:
      - apt-get update && apt-get install -y build-essential git mercurial subversion gperf gettext libtool libtool-bin cmake yasm zlib1g-dev autoconf pkg-config autopoint wget curl libgles2-mesa-dev
      - EXTRA=/opt/msprod/sysroot ./check.sh