pipeline:
  build_deps_and_check:
    image: debian:buster
    commands:
      - apt-get update && apt-get -y install build-essential git mercurial subversion gperf gettext libtool libtool-bin cmake yasm zlib1g-dev autoconf pkg-config autopoint wget curl libgles2-mesa-dev&&  update-ca-certificates
      - ./extra.sh
      - EXTRA=/opt/msprod/sysroot ./check.sh