FROM ubuntu:24.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV SIGNALS_REPO=https://github.com/MotionSpell/signals.git
ENV BUILD_DIR=/signals

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    tzdata \
    zip \
    unzip \
    curl \
    tar \
    git \
    ca-certificates \
    linux-libc-dev \
    build-essential \
    pkg-config \
    yasm \
    nasm \
    autoconf \
    automake \
    autoconf-archive \
    autotools-dev \
    python3 \
    python3-jinja2 \
    gcc \
    g++ \
    make && \
    rm -Rf /var/lib/apt/lists/*

# Set environment variables for cmake and ninja
ENV CMAKE_ROOT=/opt/cmake
ENV NINJA_ROOT=/opt/ninja

ENV PATH=${NINJA_ROOT}:${CMAKE_ROOT}/bin:${PATH}

# Copy version and install scripts
COPY version_cmake.env install_cmake.sh /opt/

# Download, build and install tools
RUN cd /opt && \
    chmod a+x install_cmake.sh && \
    ./install_cmake.sh ${NINJA_ROOT} ${CMAKE_ROOT} && \
    rm install_cmake.sh && rm version_cmake.env

# Clone the Signals repository
RUN git clone --recurse-submodules -b vcpkg-cmake ${SIGNALS_REPO} ${BUILD_DIR}

# Set working directory
WORKDIR ${BUILD_DIR}

# Update submodules
RUN git submodule update --remote vcpkg

# fix for libcrypto build 
RUN apt-get update && \
    apt-get install -y libtool && \
    libtoolize --copy --force

# Configure and build the project
RUN cmake  --preset linux-develop
RUN cmake --build build --preset linux-develop

# Set the entry point
ENTRYPOINT ["/bin/bash"]
