name: Windows Build

on:
  push:
    branches:
      - vcpkg-cmake
  pull_request:
    branches:
      - vcpkg-cmake

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Set up environment variables
      run: |
        echo "BUILD_DIR=${{ github.workspace }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "VCPKG_DEFAULT_TRIPLET=x64-mingw-dynamic" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-nasm
          mingw-w64-x86_64-yasm
          mingw-w64-x86_64-autotools
          git
          make

    - name: Set MSYS2 path
      run: |
        echo "C:\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "MSYSTEM=MINGW64" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh

    - name: Setup vcpkg
      run: |
        git submodule update --init --recursive
        .\vcpkg\bootstrap-vcpkg.bat
      shell: cmd

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. --preset mingw-production -DCMAKE_BUILD_TYPE=Release
      shell: bash

    - name: Build
      working-directory: build
      run: cmake --build . --config Release
      shell: bash

    - name: Test
      working-directory: build
      run: ctest -C Release --output-on-failure
      shell: bash

    - name: Upload logs on failure
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: build-logs
        path: |
          build/CMakeFiles/CMakeOutput.log
          build/CMakeFiles/CMakeError.log
          vcpkg/buildtrees/**/*.log
