name: Windows Build

on:
  push:
    branches:
      - vcpkg-cmake
  pull_request:
    branches:
      - vcpkg-cmake

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up environment variables
      run: |
        echo "SIGNALS_REPO=https://github.com/MotionSpell/signals.git" >> $GITHUB_ENV
        echo "BUILD_DIR=C:/signals" >> $GITHUB_ENV
        echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
        echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          make
          git
          cmake
          ninja
          unzip

    - name: Set environment variables for MSYS2
      run: |
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        echo "C:\msys64\usr\bin" >> $GITHUB_PATH
        echo "MSYSTEM=MINGW64" >> $GITHUB_ENV
      shell: bash

    - name: Initialize vcpkg submodule
      run: git submodule update --init --recursive
      shell: bash

    - name: Bootstrap vcpkg
      run: vcpkg/bootstrap-vcpkg.bat
      shell: cmd

    - name: Clone the Signals repository
      run: git clone --recurse-submodules -b vcpkg-cmake $SIGNALS_REPO $BUILD_DIR
      shell: bash

    - name: Update submodules
      run: cd $BUILD_DIR && git submodule update --remote vcpkg
      shell: bash

    - name: Configure CMake
      run: cd $BUILD_DIR && cmake --preset mingw-production
      shell: bash

    - name: Build the project
      run: cd $BUILD_DIR && cmake --build --preset mingw-production
      shell: bash

    - name: Run tests
      run: cd $BUILD_DIR && ctest --output-on-failure
      shell: bash
