name: Windows Build

on:
  push:
    branches:
      - vcpkg-cmake
  pull_request:
    branches:
      - vcpkg-cmake

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up environment variables
      run: |
        echo "BUILD_DIR=${{ github.workspace }}" >> $GITHUB_ENV
        echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
        echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-toolchain
          make
          git
          cmake
          ninja
          unzip

    - name: Set environment variables for MSYS2
      run: |
        echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
        echo "C:\msys64\usr\bin" >> $GITHUB_PATH
        echo "MSYSTEM=MINGW64" >> $GITHUB_ENV
      shell: bash

    - name: Initialize vcpkg submodule
      run: git submodule update --init --recursive
      shell: bash

    - name: Bootstrap vcpkg
      run: vcpkg/bootstrap-vcpkg.bat
      shell: cmd

    - name: Update submodules
      run: git submodule update --remote vcpkg
      shell: bash

    - name: Configure CMake
      run: cmake --preset mingw-production
      shell: bash

    - name: Build the project
      run: cmake --build --preset mingw-production
      shell: bash

    - name: Run tests
      run: ctest --output-on-failure
      shell: bash
